# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  google_provider_key: <%= ENV["GOOGLE_PROVIDER_KEY"] %>
  google_provider_secret: <%= ENV["GOOGLE_PROVIDER_SECRET"] %>
  trello_provider_key: <%= ENV["TRELLO_PROVIDER_KEY"] %>
  trello_provider_secret: <%= ENV["TRELLO_PROVIDER_SECRET"] %>
  beeminder_provider_key: <%= ENV["BEEMINDER_PROVIDER_KEY"] %>
  beeminder_provider_secret: <%= ENV["BEEMINDER_PROVIDER_SECRET"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  pocket_provider_key: <%= ENV["POCKET_PROVIDER_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"]  %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  dumper_app_key: <%= ENV['DUMPER_APP_KEY'] %>

test:
  <<: *default

production: &development
  <<: *default
